export const COUNTRY_META = {
  Afghanistan: {
    isd: "+93",
    iso2: "AF",
    states: [
      "Badakhshan",
      "Badghis",
      "Baghlan",
      "Balkh",
      "Bamyan",
      "Daykundi",
      "Farah",
      "Faryab",
      "Ghazni",
      "Ghor",
      "Helmand",
      "Herat",
      "Jowzjan",
      "Kabul",
      "Kandahar",
      "Kapisa",
      "Khost",
      "Kunar",
      "Kunduz",
      "Laghman",
      "Logar",
      "Nangarhar",
      "Nimroz",
      "Nuristan",
      "Paktia",
      "Paktika",
      "Panjshir",
      "Parwan",
      "Samangan",
      "Sar-e Pol",
      "Takhar",
      "Urozgan",
      "Wardak",
      "Zabul",
    ],
  },
  Albania: {
    isd: "+355",
    iso2: "AL",
    states: [
      "Berat",
      "Dibër",
      "Durrës",
      "Elbasan",
      "Fier",
      "Gjirokastër",
      "Korçë",
      "Kukës",
      "Lezhë",
      "Shkodër",
      "Tiranë",
      "Vlorë",
    ],
  },
  Algeria: {
    isd: "+213",
    iso2: "DZ",
    states: [
      "Adrar",
      "Ain Defla",
      "Ain Temouchent",
      "Algiers",
      "Annaba",
      "Batna",
      "Béchar",
      "Béjaïa",
      "Biskra",
      "Blida",
      "Bordj Bou Arréridj",
      "Bouira",
      "Boumerdès",
      "Chlef",
      "Constantine",
      "Djelfa",
      "El Bayadh",
      "El Oued",
      "El Tarf",
      "Ghardaïa",
      "Guelma",
      "Illizi",
      "Jijel",
      "Khenchela",
      "Laghouat",
      "Mascara",
      "Médéa",
      "Mila",
      "Mostaganem",
      "Msila",
      "Naâma",
      "Oran",
      "Ouargla",
      "Oum El Bouaghi",
      "Relizane",
      "Saïda",
      "Sétif",
      "Sidi Bel Abbès",
      "Skikda",
      "Souk Ahras",
      "Tamanrasset",
      "Tébessa",
      "Tiaret",
      "Tindouf",
      "Tipaza",
      "Tissemsilt",
      "Tizi Ouzou",
      "Tlemcen",
    ],
  },
  Andorra: {
    isd: "+376",
    iso2: "AD",
    states: [
      "Andorra la Vella",
      "Canillo",
      "Encamp",
      "Escaldes-Engordany",
      "La Massana",
      "Ordino",
      "Sant Julià de Lòria",
    ],
  },
  Angola: {
    isd: "+244",
    iso2: "AO",
    states: [
      "Bengo",
      "Benguela",
      "Bié",
      "Cabinda",
      "Cuando Cubango",
      "Cuanza Norte",
      "Cuanza Sul",
      "Cunene",
      "Huambo",
      "Huíla",
      "Luanda",
      "Lunda Norte",
      "Lunda Sul",
      "Malanje",
      "Moxico",
      "Namibe",
      "Uíge",
      "Zaire",
    ],
  },
  Argentina: {
    isd: "+54",
    iso2: "AR",
    states: [
      "Buenos Aires",
      "Catamarca",
      "Chaco",
      "Chubut",
      "Córdoba",
      "Corrientes",
      "Entre Ríos",
      "Formosa",
      "Jujuy",
      "La Pampa",
      "La Rioja",
      "Mendoza",
      "Misiones",
      "Neuquén",
      "Río Negro",
      "Salta",
      "San Juan",
      "San Luis",
      "Santa Cruz",
      "Santa Fe",
      "Santiago del Estero",
      "Tierra del Fuego",
      "Tucumán",
    ],
  },
  Armenia: {
    isd: "+374",
    iso2: "AM",
    states: [
      "Aragatsotn",
      "Ararat",
      "Armavir",
      "Gegharkunik",
      "Kotayk",
      "Lori",
      "Shirak",
      "Syunik",
      "Tavush",
      "Vayots Dzor",
      "Yerevan",
    ],
  },
  Australia: {
    isd: "+61",
    iso2: "AU",
    states: [
      "Australian Capital Territory",
      "New South Wales",
      "Northern Territory",
      "Queensland",
      "South Australia",
      "Tasmania",
      "Victoria",
      "Western Australia",
    ],
  },
  Austria: {
    isd: "+43",
    iso2: "AT",
    states: [
      "Burgenland",
      "Carinthia",
      "Lower Austria",
      "Salzburg",
      "Styria",
      "Tyrol",
      "Upper Austria",
      "Vienna",
      "Vorarlberg",
    ],
  },
  Azerbaijan: {
    isd: "+994",
    iso2: "AZ",
    states: [
      "Absheron",
      "Agdam",
      "Agdash",
      "Aghjabadi",
      "Agstafa",
      "Agsu",
      "Astara",
      "Baku",
      "Balakan",
      "Barda",
      "Beylagan",
      "Bilasuvar",
      "Dashkasan",
      "Fuzuli",
      "Gadabay",
      "Ganja",
      "Gobustan",
      "Goranboy",
      "Goychay",
      "Goygol",
      "Hajigabul",
      "Imishli",
      "Ismailli",
      "Jabrayil",
      "Jalilabad",
      "Kalbajar",
      "Kurdamir",
      "Lachin",
      "Lankaran",
      "Lerik",
      "Masally",
      "Mingachevir",
      "Nakhchivan",
      "Neftchala",
      "Oghuz",
      "Qabala",
      "Qakh",
      "Qazakh",
      "Quba",
      "Qubadli",
      "Qusar",
      "Saatly",
      "Sabirabad",
      "Salyan",
      "Shamakhi",
      "Shamkir",
      "Shirvan",
      "Shusha",
      "Siazan",
      "Sumgayit",
      "Tartar",
      "Tovuz",
      "Ujar",
      "Khachmaz",
      "Khankendi",
      "Khizi",
      "Yardymly",
      "Yevlakh",
      "Zangilan",
      "Zaqatala",
      "Zardab",
    ],
  },
  Bahamas: {
    isd: "+1-242",
    iso2: "BS",
    states: [
      "Acklins",
      "Berry Islands",
      "Bimini",
      "Black Point",
      "Cat Island",
      "Central Abaco",
      "Central Andros",
      "Central Eleuthera",
      "City of Freeport",
      "Crooked Island and Long Cay",
      "East Grand Bahama",
      "Exuma",
      "Grand Cay",
      "Harbour Island",
      "Hope Town",
      "Inagua",
      "Long Island",
      "Mangrove Cay",
      "Mayaguana",
      "Moore's Island",
      "New Providence",
      "North Abaco",
      "North Andros",
      "North Eleuthera",
      "Ragged Island",
      "Rum Cay",
      "San Salvador",
      "South Abaco",
      "South Andros",
      "South Eleuthera",
      "Spanish Wells",
      "West Grand Bahama",
    ],
  },
  Bahrain: {
    isd: "+973",
    iso2: "BH",
    states: ["Capital", "Muharraq", "Northern", "Southern"],
  },
  Bangladesh: {
    isd: "+880",
    iso2: "BD",
    states: [
      "Barisal",
      "Chittagong",
      "Dhaka",
      "Khulna",
      "Mymensingh",
      "Rajshahi",
      "Rangpur",
      "Sylhet",
    ],
  },
  Barbados: {
    isd: "+1-246",
    iso2: "BB",
    states: [
      "Christ Church",
      "Saint Andrew",
      "Saint George",
      "Saint James",
      "Saint John",
      "Saint Joseph",
      "Saint Lucy",
      "Saint Michael",
      "Saint Peter",
      "Saint Philip",
      "Saint Thomas",
    ],
  },
  Belarus: {
    isd: "+375",
    iso2: "BY",
    states: ["Brest", "Gomel", "Grodno", "Minsk", "Mogilev", "Vitebsk"],
  },
  Belgium: {
    isd: "+32",
    iso2: "BE",
    states: [
      "Antwerp",
      "Brussels",
      "East Flanders",
      "Flemish Brabant",
      "Hainaut",
      "Liège",
      "Limburg",
      "Luxembourg",
      "Namur",
      "Walloon Brabant",
      "West Flanders",
    ],
  },
  Belize: {
    isd: "+501",
    iso2: "BZ",
    states: [
      "Belize",
      "Cayo",
      "Corozal",
      "Orange Walk",
      "Stann Creek",
      "Toledo",
    ],
  },
  Benin: {
    isd: "+229",
    iso2: "BJ",
    states: [
      "Alibori",
      "Atakora",
      "Atlantique",
      "Borgou",
      "Collines",
      "Couffo",
      "Donga",
      "Littoral",
      "Mono",
      "Ouémé",
      "Plateau",
      "Zou",
    ],
  },
  Bhutan: {
    isd: "+975",
    iso2: "BT",
    states: [
      "Bumthang",
      "Chhukha",
      "Dagana",
      "Gasa",
      "Haa",
      "Lhuntse",
      "Mongar",
      "Paro",
      "Pemagatshel",
      "Punakha",
      "Samdrup Jongkhar",
      "Samtse",
      "Sarpang",
      "Thimphu",
      "Trashigang",
      "Trashi Yangtse",
      "Trongsa",
      "Tsirang",
      "Wangdue Phodrang",
      "Zhemgang",
    ],
  },
  Bolivia: {
    isd: "+591",
    iso2: "BO",
    states: [
      "Beni",
      "Chuquisaca",
      "Cochabamba",
      "La Paz",
      "Oruro",
      "Pando",
      "Potosí",
      "Santa Cruz",
      "Tarija",
    ],
  },
  "Bosnia and Herzegovina": {
    isd: "+387",
    iso2: "BA",
    states: [
      "Bosnian Podrinje",
      "Brčko",
      "Canton 10",
      "Central Bosnia",
      "Herzegovina-Neretva",
      "Posavina",
      "Sarajevo",
      "Tuzla",
      "Una-Sana",
      "West Herzegovina",
      "Zenica-Doboj",
    ],
  },
  Botswana: {
    isd: "+267",
    iso2: "BW",
    states: [
      "Central",
      "Ghanzi",
      "Kgalagadi",
      "Kgatleng",
      "Kweneng",
      "North East",
      "North West",
      "South East",
      "Southern",
    ],
  },
  Brazil: {
    isd: "+55",
    iso2: "BR",
    states: [
      "Acre",
      "Alagoas",
      "Amapá",
      "Amazonas",
      "Bahia",
      "Ceará",
      "Distrito Federal",
      "Espírito Santo",
      "Goiás",
      "Maranhão",
      "Mato Grosso",
      "Mato Grosso do Sul",
      "Minas Gerais",
      "Pará",
      "Paraíba",
      "Paraná",
      "Pernambuco",
      "Piauí",
      "Rio de Janeiro",
      "Rio Grande do Norte",
      "Rio Grande do Sul",
      "Rondônia",
      "Roraima",
      "Santa Catarina",
      "São Paulo",
      "Sergipe",
      "Tocantins",
    ],
  },
  Brunei: {
    isd: "+673",
    iso2: "BN",
    states: ["Belait", "Brunei-Muara", "Temburong", "Tutong"],
  },
  Bulgaria: {
    isd: "+359",
    iso2: "BG",
    states: [
      "Blagoevgrad",
      "Burgas",
      "Dobrich",
      "Gabrovo",
      "Haskovo",
      "Kardzhali",
      "Kyustendil",
      "Lovech",
      "Montana",
      "Pazardzhik",
      "Pernik",
      "Pleven",
      "Plovdiv",
      "Razgrad",
      "Ruse",
      "Shumen",
      "Silistra",
      "Sliven",
      "Smolyan",
      "Sofia",
      "Sofia Province",
      "Stara Zagora",
      "Targovishte",
      "Varna",
      "Veliko Tarnovo",
      "Vidin",
      "Vratsa",
      "Yambol",
    ],
  },
  "Burkina Faso": {
    isd: "+226",
    iso2: "BF",
    states: [
      "Boucle du Mouhoun",
      "Cascades",
      "Centre",
      "Centre-Est",
      "Centre-Nord",
      "Centre-Ouest",
      "Centre-Sud",
      "Est",
      "Hauts-Bassins",
      "Nord",
      "Plateau-Central",
      "Sahel",
      "Sud-Ouest",
    ],
  },
  Burundi: {
    isd: "+257",
    iso2: "BI",
    states: [
      "Bubanza",
      "Bujumbura Mairie",
      "Bujumbura Rural",
      "Bururi",
      "Cankuzo",
      "Cibitoke",
      "Gitega",
      "Karuzi",
      "Kayanza",
      "Kirundo",
      "Makamba",
      "Muramvya",
      "Muyinga",
      "Mwaro",
      "Ngozi",
      "Rumonge",
      "Rutana",
      "Ruyigi",
    ],
  },
  Cambodia: {
    isd: "+855",
    iso2: "KH",
    states: [
      "Banteay Meanchey",
      "Battambang",
      "Kampong Cham",
      "Kampong Chhnang",
      "Kampong Speu",
      "Kampong Thom",
      "Kampot",
      "Kandal",
      "Kep",
      "Koh Kong",
      "Kratie",
      "Mondulkiri",
      "Oddar Meanchey",
      "Pailin",
      "Phnom Penh",
      "Preah Sihanouk",
      "Preah Vihear",
      "Prey Veng",
      "Pursat",
      "Ratanakiri",
      "Siem Reap",
      "Stung Treng",
      "Svay Rieng",
      "Takéo",
      "Tboung Khmum",
    ],
  },
  Cameroon: {
    isd: "+237",
    iso2: "CM",
    states: [
      "Adamawa",
      "Centre",
      "East",
      "Far North",
      "Littoral",
      "North",
      "Northwest",
      "South",
      "Southwest",
      "West",
    ],
  },
  Canada: {
    isd: "+1",
    iso2: "CA",
    states: [
      "Alberta",
      "British Columbia",
      "Manitoba",
      "New Brunswick",
      "Newfoundland and Labrador",
      "Northwest Territories",
      "Nova Scotia",
      "Nunavut",
      "Ontario",
      "Prince Edward Island",
      "Quebec",
      "Saskatchewan",
      "Yukon",
    ],
  },
  "Cape Verde": {
    isd: "+238",
    iso2: "CV",
    states: [
      "Boa Vista",
      "Brava",
      "Maio",
      "Mosteiros",
      "Paul",
      "Porto Novo",
      "Praia",
      "Ribeira Brava",
      "Ribeira Grande",
      "Ribeira Grande de Santiago",
      "Sal",
      "Santa Catarina",
      "Santa Catarina do Fogo",
      "Santa Cruz",
      "São Domingos",
      "São Filipe",
      "São Lourenço dos Órgãos",
      "São Miguel",
      "São Salvador do Mundo",
      "São Vicente",
      "Tarrafal",
      "Tarrafal de São Nicolau",
    ],
  },
  "Central African Republic": {
    isd: "+236",
    iso2: "CF",
    states: [
      "Bamingui-Bangoran",
      "Bangui",
      "Basse-Kotto",
      "Haute-Kotto",
      "Haut-Mbomou",
      "Kémo",
      "Lobaye",
      "Mambéré-Kadéï",
      "Mbomou",
      "Nana-Grébizi",
      "Nana-Mambéré",
      "Ombella-M'Poko",
      "Ouaka",
      "Ouham",
      "Ouham-Pendé",
      "Sangha-Mbaéré",
      "Vakaga",
    ],
  },
  Chad: {
    isd: "+235",
    iso2: "TD",
    states: [
      "Bahr el Gazel",
      "Batha",
      "Borkou",
      "Chari-Baguirmi",
      "Ennedi Est",
      "Ennedi Ouest",
      "Guéra",
      "Hadjer-Lamis",
      "Kanem",
      "Lac",
      "Logone Occidental",
      "Logone Oriental",
      "Mandoul",
      "Mayo-Kebbi Est",
      "Mayo-Kebbi Ouest",
      "Moyen-Chari",
      "N'Djamena",
      "Ouaddaï",
      "Salamat",
      "Sila",
      "Tandjilé",
      "Tibesti",
      "Wadi Fira",
    ],
  },
  Chile: {
    isd: "+56",
    iso2: "CL",
    states: [
      "Araucanía",
      "Arica y Parinacota",
      "Atacama",
      "Aysén",
      "Biobío",
      "Coquimbo",
      "La Araucanía",
      "Los Lagos",
      "Los Ríos",
      "Magallanes",
      "Maule",
      "Metropolitana de Santiago",
      "Ñuble",
      "O'Higgins",
      "Tarapacá",
      "Valparaíso",
    ],
  },
  China: {
    isd: "+86",
    iso2: "CN",
    states: [
      "Anhui",
      "Beijing",
      "Chongqing",
      "Fujian",
      "Gansu",
      "Guangdong",
      "Guangxi",
      "Guizhou",
      "Hainan",
      "Hebei",
      "Heilongjiang",
      "Henan",
      "Hong Kong",
      "Hubei",
      "Hunan",
      "Inner Mongolia",
      "Jiangsu",
      "Jiangxi",
      "Jilin",
      "Liaoning",
      "Macau",
      "Ningxia",
      "Qinghai",
      "Shaanxi",
      "Shandong",
      "Shanghai",
      "Shanxi",
      "Sichuan",
      "Tianjin",
      "Tibet",
      "Xinjiang",
      "Yunnan",
      "Zhejiang",
    ],
  },
  Colombia: {
    isd: "+57",
    iso2: "CO",
    states: [
      "Amazonas",
      "Antioquia",
      "Arauca",
      "Atlántico",
      "Bolívar",
      "Boyacá",
      "Caldas",
      "Caquetá",
      "Casanare",
      "Cauca",
      "Cesar",
      "Chocó",
      "Córdoba",
      "Cundinamarca",
      "Guainía",
      "Guaviare",
      "Huila",
      "La Guajira",
      "Magdalena",
      "Meta",
      "Nariño",
      "Norte de Santander",
      "Putumayo",
      "Quindío",
      "Risaralda",
      "San Andrés",
      "Santander",
      "Sucre",
      "Tolima",
      "Valle del Cauca",
      "Vaupés",
      "Vichada",
    ],
  },
  Comoros: {
    isd: "+269",
    iso2: "KM",
    states: ["Anjouan", "Grande Comore", "Mohéli"],
  },
  Congo: {
    isd: "+242",
    iso2: "CG",
    states: [
      "Bouenza",
      "Brazzaville",
      "Cuvette",
      "Cuvette-Ouest",
      "Kouilou",
      "Lékoumou",
      "Likouala",
      "Niari",
      "Plateaux",
      "Pool",
      "Sangha",
    ],
  },
  "Costa Rica": {
    isd: "+506",
    iso2: "CR",
    states: [
      "Alajuela",
      "Cartago",
      "Guanacaste",
      "Heredia",
      "Limón",
      "Puntarenas",
      "San José",
    ],
  },
  Croatia: {
    isd: "+385",
    iso2: "HR",
    states: [
      "Bjelovar-Bilogora",
      "Brod-Posavina",
      "Dubrovnik-Neretva",
      "Istria",
      "Karlovac",
      "Koprivnica-Križevci",
      "Krapina-Zagorje",
      "Lika-Senj",
      "Međimurje",
      "Osijek-Baranja",
      "Požega-Slavonia",
      "Primorje-Gorski Kotar",
      "Šibenik-Knin",
      "Sisak-Moslavina",
      "Split-Dalmatia",
      "Varaždin",
      "Virovitica-Podravina",
      "Vukovar-Syrmia",
      "Zadar",
      "Zagreb County",
      "Zagreb",
    ],
  },
  Cuba: {
    isd: "+53",
    iso2: "CU",
    states: [
      "Artemisa",
      "Camagüey",
      "Ciego de Ávila",
      "Cienfuegos",
      "Granma",
      "Guantánamo",
      "Havana",
      "Holguín",
      "Isla de la Juventud",
      "Las Tunas",
      "Matanzas",
      "Mayabeque",
      "Pinar del Río",
      "Sancti Spíritus",
      "Santiago de Cuba",
      "Villa Clara",
    ],
  },
  Cyprus: {
    isd: "+357",
    iso2: "CY",
    states: [
      "Famagusta",
      "Kyrenia",
      "Larnaca",
      "Limassol",
      "Nicosia",
      "Paphos",
    ],
  },
  "Czech Republic": {
    isd: "+420",
    iso2: "CZ",
    states: [
      "Central Bohemian",
      "Hradec Králové",
      "Karlovy Vary",
      "Liberec",
      "Moravian-Silesian",
      "Olomouc",
      "Pardubice",
      "Plzeň",
      "Prague",
      "South Bohemian",
      "South Moravian",
      "Ústí nad Labem",
      "Vysočina",
      "Zlín",
    ],
  },
  "Democratic Republic of the Congo": {
    isd: "+243",
    iso2: "CD",
    states: [
      "Bas-Uele",
      "Équateur",
      "Haut-Katanga",
      "Haut-Lomami",
      "Haut-Uele",
      "Ituri",
      "Kasaï",
      "Kasaï-Central",
      "Kasaï-Oriental",
      "Kinshasa",
      "Kongo Central",
      "Kwango",
      "Kwilu",
      "Lomami",
      "Lualaba",
      "Mai-Ndombe",
      "Maniema",
      "Mongala",
      "Nord-Kivu",
      "Nord-Ubangi",
      "Sankuru",
      "South Kivu",
      "Sud-Ubangi",
      "Tanganyika",
      "Tshopo",
      "Tshuapa",
    ],
  },
  Denmark: {
    isd: "+45",
    iso2: "DK",
    states: [
      "Capital Region",
      "Central Denmark",
      "North Denmark",
      "Region Zealand",
      "Southern Denmark",
    ],
  },
  Djibouti: {
    isd: "+253",
    iso2: "DJ",
    states: ["Ali Sabieh", "Arta", "Dikhil", "Djibouti", "Obock", "Tadjourah"],
  },
  Dominica: {
    isd: "+1-767",
    iso2: "DM",
    states: [
      "Saint Andrew",
      "Saint David",
      "Saint George",
      "Saint John",
      "Saint Joseph",
      "Saint Luke",
      "Saint Mark",
      "Saint Patrick",
      "Saint Paul",
      "Saint Peter",
    ],
  },
  "Dominican Republic": {
    isd: "+1-809",
    iso2: "DO",
    states: [
      "Azua",
      "Bahoruco",
      "Barahona",
      "Dajabón",
      "Distrito Nacional",
      "Duarte",
      "El Seibo",
      "Elías Piña",
      "Espaillat",
      "Hato Mayor",
      "Hermanas Mirabal",
      "Independencia",
      "La Altagracia",
      "La Romana",
      "La Vega",
      "María Trinidad Sánchez",
      "Monseñor Nouel",
      "Monte Cristi",
      "Monte Plata",
      "Pedernales",
      "Peravia",
      "Puerto Plata",
      "Samaná",
      "San Cristóbal",
      "San José de Ocoa",
      "San Juan",
      "San Pedro de Macorís",
      "Sánchez Ramírez",
      "Santiago",
      "Santiago Rodríguez",
      "Santo Domingo",
      "Valverde",
    ],
  },
  Ecuador: {
    isd: "+593",
    iso2: "EC",
    states: [
      "Azuay",
      "Bolívar",
      "Cañar",
      "Carchi",
      "Chimborazo",
      "Cotopaxi",
      "El Oro",
      "Esmeraldas",
      "Galápagos",
      "Guayas",
      "Imbabura",
      "Loja",
      "Los Ríos",
      "Manabí",
      "Morona-Santiago",
      "Napo",
      "Orellana",
      "Pastaza",
      "Pichincha",
      "Santa Elena",
      "Santo Domingo de los Tsáchilas",
      "Sucumbíos",
      "Tungurahua",
      "Zamora-Chinchipe",
    ],
  },
  Egypt: {
    isd: "+20",
    iso2: "EG",
    states: [
      "Alexandria",
      "Aswan",
      "Asyut",
      "Beheira",
      "Beni Suef",
      "Cairo",
      "Dakahlia",
      "Damietta",
      "Faiyum",
      "Gharbia",
      "Giza",
      "Ismailia",
      "Kafr el-Sheikh",
      "Luxor",
      "Matruh",
      "Minya",
      "Monufia",
      "New Valley",
      "North Sinai",
      "Port Said",
      "Qalyubia",
      "Qena",
      "Red Sea",
      "Sharqia",
      "Sohag",
      "South Sinai",
      "Suez",
    ],
  },
  "El Salvador": {
    isd: "+503",
    iso2: "SV",
    states: [
      "Ahuachapán",
      "Cabañas",
      "Chalatenango",
      "Cuscatlán",
      "La Libertad",
      "La Paz",
      "La Unión",
      "Morazán",
      "San Miguel",
      "San Salvador",
      "San Vicente",
      "Santa Ana",
      "Sonsonate",
      "Usulután",
    ],
  },
  "Equatorial Guinea": {
    isd: "+240",
    iso2: "GQ",
    states: [
      "Annobón",
      "Bioko Norte",
      "Bioko Sur",
      "Centro Sur",
      "Djibloho",
      "Kié-Ntem",
      "Litoral",
      "Wele-Nzas",
    ],
  },
  Eritrea: {
    isd: "+291",
    iso2: "ER",
    states: [
      "Anseba",
      "Central",
      "Gash-Barka",
      "Maekel",
      "Northern Red Sea",
      "Southern",
      "Southern Red Sea",
    ],
  },
  Estonia: {
    isd: "+372",
    iso2: "EE",
    states: [
      "Harju",
      "Hiiu",
      "Ida-Viru",
      "Järva",
      "Jõgeva",
      "Lääne",
      "Lääne-Viru",
      "Pärnu",
      "Põlva",
      "Rapla",
      "Saare",
      "Tartu",
      "Valga",
      "Viljandi",
      "Võru",
    ],
  },
  Eswatini: {
    isd: "+268",
    iso2: "SZ",
    states: ["Hhohho", "Lubombo", "Manzini", "Shiselweni"],
  },
  Ethiopia: {
    isd: "+251",
    iso2: "ET",
    states: [
      "Addis Ababa",
      "Afar",
      "Amhara",
      "Benishangul-Gumuz",
      "Dire Dawa",
      "Gambela",
      "Harari",
      "Oromia",
      "Sidama",
      "Somali",
      "South West Ethiopia Peoples",
      "Southern Nations",
      "Tigray",
    ],
  },
  Fiji: {
    isd: "+679",
    iso2: "FJ",
    states: [
      "Ba",
      "Bua",
      "Cakaudrove",
      "Kadavu",
      "Lau",
      "Lomaiviti",
      "Macuata",
      "Nadroga-Navosa",
      "Naitasiri",
      "Namosi",
      "Ra",
      "Rewa",
      "Rotuma",
      "Serua",
      "Tailevu",
    ],
  },
  Finland: {
    isd: "+358",
    iso2: "FI",
    states: [
      "Åland Islands",
      "Central Finland",
      "Central Ostrobothnia",
      "Kainuu",
      "Kanta-Häme",
      "Kymenlaakso",
      "Lapland",
      "North Karelia",
      "North Ostrobothnia",
      "North Savo",
      "Ostrobothnia",
      "Päijät-Häme",
      "Pirkanmaa",
      "Satakunta",
      "South Karelia",
      "South Ostrobothnia",
      "South Savo",
      "Southwest Finland",
      "Uusimaa",
    ],
  },
  France: {
    isd: "+33",
    iso2: "FR",
    states: [
      "Auvergne-Rhône-Alpes",
      "Bourgogne-Franche-Comté",
      "Brittany",
      "Centre-Val de Loire",
      "Corsica",
      "Grand Est",
      "Hauts-de-France",
      "Île-de-France",
      "Normandy",
      "Nouvelle-Aquitaine",
      "Occitanie",
      "Pays de la Loire",
      "Provence-Alpes-Côte d'Azur",
    ],
  },
  Gabon: {
    isd: "+241",
    iso2: "GA",
    states: [
      "Estuaire",
      "Haut-Ogooué",
      "Moyen-Ogooué",
      "Ngounié",
      "Nyanga",
      "Ogooué-Ivindo",
      "Ogooué-Lolo",
      "Ogooué-Maritime",
      "Woleu-Ntem",
    ],
  },
  Gambia: {
    isd: "+220",
    iso2: "GM",
    states: [
      "Banjul",
      "Central River",
      "Lower River",
      "North Bank",
      "Upper River",
      "West Coast",
    ],
  },
  Georgia: {
    isd: "+995",
    iso2: "GE",
    states: [
      "Adjara",
      "Guria",
      "Imereti",
      "Kakheti",
      "Kvemo Kartli",
      "Mtskheta-Mtianeti",
      "Racha-Lechkhumi and Kvemo Svaneti",
      "Samegrelo-Zemo Svaneti",
      "Samtskhe-Javakheti",
      "Shida Kartli",
      "Tbilisi",
    ],
  },
  Germany: {
    isd: "+49",
    iso2: "DE",
    states: [
      "Baden-Württemberg",
      "Bavaria",
      "Berlin",
      "Brandenburg",
      "Bremen",
      "Hamburg",
      "Hesse",
      "Lower Saxony",
      "Mecklenburg-Vorpommern",
      "North Rhine-Westphalia",
      "Rhineland-Palatinate",
      "Saarland",
      "Saxony",
      "Saxony-Anhalt",
      "Schleswig-Holstein",
      "Thuringia",
    ],
  },
  Ghana: {
    isd: "+233",
    iso2: "GH",
    states: [
      "Ahafo",
      "Ashanti",
      "Bono",
      "Bono East",
      "Central",
      "Eastern",
      "Greater Accra",
      "North East",
      "Northern",
      "Oti",
      "Savannah",
      "Upper East",
      "Upper West",
      "Volta",
      "Western",
      "Western North",
    ],
  },
  Greece: {
    isd: "+30",
    iso2: "GR",
    states: [
      "Attica",
      "Central Greece",
      "Central Macedonia",
      "Crete",
      "Eastern Macedonia and Thrace",
      "Epirus",
      "Ionian Islands",
      "North Aegean",
      "Peloponnese",
      "South Aegean",
      "Thessaly",
      "Western Greece",
      "Western Macedonia",
    ],
  },
  Grenada: {
    isd: "+1-473",
    iso2: "GD",
    states: [
      "Carriacou and Petite Martinique",
      "Saint Andrew",
      "Saint David",
      "Saint George",
      "Saint John",
      "Saint Mark",
      "Saint Patrick",
    ],
  },
  Guatemala: {
    isd: "+502",
    iso2: "GT",
    states: [
      "Alta Verapaz",
      "Baja Verapaz",
      "Chimaltenango",
      "Chiquimula",
      "El Progreso",
      "Escuintla",
      "Guatemala",
      "Huehuetenango",
      "Izabal",
      "Jalapa",
      "Jutiapa",
      "Petén",
      "Quetzaltenango",
      "Quiché",
      "Retalhuleu",
      "Sacatepéquez",
      "San Marcos",
      "Santa Rosa",
      "Sololá",
      "Suchitepéquez",
      "Totonicapán",
      "Zacapa",
    ],
  },
  Guinea: {
    isd: "+224",
    iso2: "GN",
    states: [
      "Boké",
      "Conakry",
      "Faranah",
      "Kankan",
      "Kindia",
      "Labé",
      "Mamou",
      "Nzérékoré",
    ],
  },
  "Guinea-Bissau": {
    isd: "+245",
    iso2: "GW",
    states: [
      "Bafatá",
      "Biombo",
      "Bissau",
      "Bolama",
      "Cacheu",
      "Gabú",
      "Oio",
      "Quinara",
      "Tombali",
    ],
  },
  Guyana: {
    isd: "+592",
    iso2: "GY",
    states: [
      "Barima-Waini",
      "Cuyuni-Mazaruni",
      "Demerara-Mahaica",
      "East Berbice-Corentyne",
      "Essequibo Islands-West Demerara",
      "Mahaica-Berbice",
      "Pomeroon-Supenaam",
      "Potaro-Siparuni",
      "Upper Demerara-Berbice",
      "Upper Takutu-Upper Essequibo",
    ],
  },
  Haiti: {
    isd: "+509",
    iso2: "HT",
    states: [
      "Artibonite",
      "Centre",
      "Grand'Anse",
      "Nippes",
      "Nord",
      "Nord-Est",
      "Nord-Ouest",
      "Ouest",
      "Sud",
      "Sud-Est",
    ],
  },
  Honduras: {
    isd: "+504",
    iso2: "HN",
    states: [
      "Atlántida",
      "Choluteca",
      "Colón",
      "Comayagua",
      "Copán",
      "Cortés",
      "El Paraíso",
      "Francisco Morazán",
      "Gracias a Dios",
      "Intibucá",
      "Islas de la Bahía",
      "La Paz",
      "Lempira",
      "Ocotepeque",
      "Olancho",
      "Santa Bárbara",
      "Valle",
      "Yoro",
    ],
  },
  Hungary: {
    isd: "+36",
    iso2: "HU",
    states: [
      "Bács-Kiskun",
      "Baranya",
      "Békés",
      "Borsod-Abaúj-Zemplén",
      "Budapest",
      "Csongrád-Csanád",
      "Fejér",
      "Győr-Moson-Sopron",
      "Hajdú-Bihar",
      "Heves",
      "Jász-Nagykun-Szolnok",
      "Komárom-Esztergom",
      "Nógrád",
      "Pest",
      "Somogy",
      "Szabolcs-Szatmár-Bereg",
      "Tolna",
      "Vas",
      "Veszprém",
      "Zala",
    ],
  },
  Iceland: {
    isd: "+354",
    iso2: "IS",
    states: [
      "Capital Region",
      "Eastern",
      "Northeastern",
      "Northwestern",
      "Southern",
      "Southern Peninsula",
      "Western",
      "Westfjords",
    ],
  },
  India: {
    isd: "+91",
    iso2: "IN",
    states: [
      "Andhra Pradesh",
      "Arunachal Pradesh",
      "Assam",
      "Bihar",
      "Chhattisgarh",
      "Goa",
      "Gujarat",
      "Haryana",
      "Himachal Pradesh",
      "Jharkhand",
      "Karnataka",
      "Kerala",
      "Madhya Pradesh",
      "Maharashtra",
      "Manipur",
      "Meghalaya",
      "Mizoram",
      "Nagaland",
      "Odisha",
      "Punjab",
      "Rajasthan",
      "Sikkim",
      "Tamil Nadu",
      "Telangana",
      "Tripura",
      "Uttar Pradesh",
      "Uttarakhand",
      "West Bengal",
      "Andaman and Nicobar Islands",
      "Chandigarh",
      "Dadra and Nagar Haveli",
      "Daman and Diu",
      "Delhi",
      "Jammu and Kashmir",
      "Ladakh",
      "Lakshadweep",
      "Puducherry",
    ],
  },
  Indonesia: {
    isd: "+62",
    iso2: "ID",
    states: [
      "Aceh",
      "Bali",
      "Bangka Belitung",
      "Banten",
      "Bengkulu",
      "Central Java",
      "Central Kalimantan",
      "Central Sulawesi",
      "East Java",
      "East Kalimantan",
      "East Nusa Tenggara",
      "Gorontalo",
      "Jakarta",
      "Jambi",
      "Lampung",
      "Maluku",
      "North Kalimantan",
      "North Maluku",
      "North Sulawesi",
      "North Sumatra",
      "Papua",
      "Riau",
      "Riau Islands",
      "South Kalimantan",
      "South Sulawesi",
      "South Sumatra",
      "Southeast Sulawesi",
      "West Java",
      "West Kalimantan",
      "West Nusa Tenggara",
      "West Papua",
      "West Sulawesi",
      "West Sumatra",
      "Yogyakarta",
    ],
  },
  Iran: {
    isd: "+98",
    iso2: "IR",
    states: [
      "Alborz",
      "Ardabil",
      "Bushehr",
      "Chaharmahal and Bakhtiari",
      "East Azerbaijan",
      "Esfahan",
      "Fars",
      "Gilan",
      "Golestan",
      "Hamadan",
      "Hormozgan",
      "Ilam",
      "Kerman",
      "Kermanshah",
      "Khuzestan",
      "Kohgiluyeh and Boyer-Ahmad",
      "Kurdistan",
      "Lorestan",
      "Markazi",
      "Mazandaran",
      "North Khorasan",
      "Qazvin",
      "Qom",
      "Razavi Khorasan",
      "Semnan",
      "Sistan and Baluchestan",
      "South Khorasan",
      "Tehran",
      "West Azerbaijan",
      "Yazd",
      "Zanjan",
    ],
  },
  Iraq: {
    isd: "+964",
    iso2: "IQ",
    states: [
      "Al Anbar",
      "Al-Qādisiyyah",
      "Babylon",
      "Baghdad",
      "Basra",
      "Dhi Qar",
      "Diyala",
      "Duhok",
      "Erbil",
      "Halabja",
      "Karbala",
      "Kirkuk",
      "Maysan",
      "Muthanna",
      "Najaf",
      "Nineveh",
      "Saladin",
      "Sulaymaniyah",
      "Wasit",
    ],
  },
  Ireland: {
    isd: "+353",
    iso2: "IE",
    states: [
      "Carlow",
      "Cavan",
      "Clare",
      "Cork",
      "Donegal",
      "Dublin",
      "Galway",
      "Kerry",
      "Kildare",
      "Kilkenny",
      "Laois",
      "Leitrim",
      "Limerick",
      "Longford",
      "Louth",
      "Mayo",
      "Meath",
      "Monaghan",
      "Offaly",
      "Roscommon",
      "Sligo",
      "Tipperary",
      "Waterford",
      "Westmeath",
      "Wexford",
      "Wicklow",
    ],
  },
  Israel: {
    isd: "+972",
    iso2: "IL",
    states: [
      "Central",
      "Haifa",
      "Jerusalem",
      "Northern",
      "Southern",
      "Tel Aviv",
    ],
  },
  Italy: {
    isd: "+39",
    iso2: "IT",
    states: [
      "Abruzzo",
      "Aosta Valley",
      "Apulia",
      "Basilicata",
      "Calabria",
      "Campania",
      "Emilia-Romagna",
      "Friuli-Venezia Giulia",
      "Lazio",
      "Liguria",
      "Lombardy",
      "Marche",
      "Molise",
      "Piedmont",
      "Sardinia",
      "Sicily",
      "Trentino-South Tyrol",
      "Tuscany",
      "Umbria",
      "Veneto",
    ],
  },
  "Ivory Coast": {
    isd: "+225",
    iso2: "CI",
    states: [
      "Abidjan",
      "Agnéby-Tiassa",
      "Bafing",
      "Bagoué",
      "Béré",
      "Bounkani",
      "Cavally",
      "Folon",
      "Gbêkê",
      "Gôh",
      "Grands-Ponts",
      "Guémon",
      "Hambol",
      "Haut-Sassandra",
      "Indénié-Djuablin",
      "Kabadougou",
      "La Mé",
      "Lôh-Djiboua",
      "Marahoué",
      "Moronou",
      "N'Zi",
      "Nawa",
      "Poro",
      "San-Pédro",
      "Tonkpi",
      "Worodougou",
      "Yamoussoukro",
      "Zanzan",
    ],
  },
  Jamaica: {
    isd: "+1-876",
    iso2: "JM",
    states: [
      "Clarendon",
      "Hanover",
      "Kingston",
      "Manchester",
      "Portland",
      "Saint Andrew",
      "Saint Ann",
      "Saint Catherine",
      "Saint Elizabeth",
      "Saint James",
      "Saint Mary",
      "Saint Thomas",
      "Trelawny",
      "Westmoreland",
    ],
  },
  Japan: {
    isd: "+81",
    iso2: "JP",
    states: [
      "Aichi",
      "Akita",
      "Aomori",
      "Chiba",
      "Ehime",
      "Fukui",
      "Fukuoka",
      "Fukushima",
      "Gifu",
      "Gunma",
      "Hiroshima",
      "Hokkaido",
      "Hyogo",
      "Ibaraki",
      "Ishikawa",
      "Iwate",
      "Kagawa",
      "Kagoshima",
      "Kanagawa",
      "Kochi",
      "Kumamoto",
      "Kyoto",
      "Mie",
      "Miyagi",
      "Miyazaki",
      "Nagano",
      "Nagasaki",
      "Nara",
      "Niigata",
      "Oita",
      "Okayama",
      "Okinawa",
      "Osaka",
      "Saga",
      "Saitama",
      "Shiga",
      "Shimane",
      "Shizuoka",
      "Tochigi",
      "Tokushima",
      "Tokyo",
      "Tottori",
      "Toyama",
      "Wakayama",
      "Yamagata",
      "Yamaguchi",
      "Yamanashi",
    ],
  },
  Jordan: {
    isd: "+962",
    iso2: "JO",
    states: [
      "Ajloun",
      "Aqaba",
      "Balqa",
      "Irbid",
      "Jarash",
      "Karak",
      "Maan",
      "Madaba",
      "Mafraq",
      "Petra",
      "Tafilah",
      "Zarqa",
      "Amman",
    ],
  },
  Kazakhstan: {
    isd: "+7",
    iso2: "KZ",
    states: [
      "Akmola",
      "Aktobe",
      "Almaty",
      "Almaty City",
      "Atyrau",
      "East Kazakhstan",
      "Karaganda",
      "Kostanay",
      "Kyzylorda",
      "Mangystau",
      "North Kazakhstan",
      "Nur-Sultan",
      "Pavlodar",
      "Shymkent",
      "Turkestan",
      "West Kazakhstan",
      "Zhambyl",
    ],
  },
  Kenya: {
    isd: "+254",
    iso2: "KE",
    states: [
      "Baringo",
      "Bomet",
      "Bungoma",
      "Busia",
      "Elgeyo-Marakwet",
      "Embu",
      "Garissa",
      "Homa Bay",
      "Isiolo",
      "Kajiado",
      "Kakamega",
      "Kericho",
      "Kiambu",
      "Kilifi",
      "Kirinyaga",
      "Kisii",
      "Kisumu",
      "Kitui",
      "Kwale",
      "Laikipia",
      "Lamu",
      "Machakos",
      "Makueni",
      "Mandera",
      "Marsabit",
      "Meru",
      "Migori",
      "Mombasa",
      "Murang'a",
      "Nairobi",
      "Nakuru",
      "Nandi",
      "Narok",
      "Nyamira",
      "Nyandarua",
      "Nyeri",
      "Samburu",
      "Siaya",
      "Taita-Taveta",
      "Tana River",
      "Tharaka-Nithi",
      "Trans-Nzoia",
      "Turkana",
      "Uasin Gishu",
      "Vihiga",
      "Wajir",
      "West Pokot",
    ],
  },
  Kuwait: {
    isd: "+965",
    iso2: "KW",
    states: [
      "Al Ahmadi",
      "Al Asimah",
      "Al Farwaniyah",
      "Al Jahra",
      "Hawalli",
      "Mubarak Al-Kabeer",
    ],
  },
  Kyrgyzstan: {
    isd: "+996",
    iso2: "KG",
    states: [
      "Batken",
      "Bishkek",
      "Chuy",
      "Issyk-Kul",
      "Jalal-Abad",
      "Naryn",
      "Osh",
      "Osh City",
      "Talas",
    ],
  },
  Laos: {
    isd: "+856",
    iso2: "LA",
    states: [
      "Attapeu",
      "Bokeo",
      "Bolikhamsai",
      "Champasak",
      "Houaphanh",
      "Khammouane",
      "Luang Namtha",
      "Luang Prabang",
      "Oudomxay",
      "Phongsaly",
      "Sainyabuli",
      "Saravane",
      "Savannakhet",
      "Sekong",
      "Vientiane",
      "Vientiane Prefecture",
      "Xaisomboun",
      "Xiangkhouang",
    ],
  },
  Latvia: {
    isd: "+371",
    iso2: "LV",
    states: [
      "Aizkraukle",
      "Alūksne",
      "Augšdaugava",
      "Ādaži",
      "Balvi",
      "Bauska",
      "Cēsis",
      "Dobele",
      "Gulbene",
      "Jelgava",
      "Jelgava Municipality",
      "Jēkabpils",
      "Jūrmala",
      "Krāslava",
      "Kuldīga",
      "Ķekava",
      "Limbaži",
      "Līvāni",
      "Ludza",
      "Madona",
      "Mārupe",
      "Ogre",
      "Olaine",
      "Preiļi",
      "Rēzekne",
      "Rēzekne Municipality",
      "Riga",
      "Ropaži",
      "Salaspils",
      "Saldus",
      "Saulkrasti",
      "Sigulda",
      "Smiltene",
      "Talsi",
      "Tukums",
      "Valka",
      "Valmiera",
      "Varakļāni",
      "Ventspils",
      "Ventspils Municipality",
    ],
  },
  Lebanon: {
    isd: "+961",
    iso2: "LB",
    states: [
      "Akkar",
      "Baalbek-Hermel",
      "Beirut",
      "Bekaa",
      "Mount Lebanon",
      "Nabatieh",
      "North Lebanon",
      "South Lebanon",
    ],
  },
  Lesotho: {
    isd: "+266",
    iso2: "LS",
    states: [
      "Berea",
      "Butha-Buthe",
      "Leribe",
      "Mafeteng",
      "Maseru",
      "Mohale's Hoek",
      "Mokhotlong",
      "Qacha's Nek",
      "Quthing",
      "Thaba-Tseka",
    ],
  },
  Liberia: {
    isd: "+231",
    iso2: "LR",
    states: [
      "Bomi",
      "Bong",
      "Gbarpolu",
      "Grand Bassa",
      "Grand Cape Mount",
      "Grand Gedeh",
      "Grand Kru",
      "Lofa",
      "Margibi",
      "Maryland",
      "Montserrado",
      "Nimba",
      "River Gee",
      "Rivercess",
      "Sinoe",
    ],
  },
  Libya: {
    isd: "+218",
    iso2: "LY",
    states: [
      "Al Butnan",
      "Al Jabal al Akhdar",
      "Al Jabal al Gharbi",
      "Al Jafarah",
      "Al Jufrah",
      "Al Kufrah",
      "Al Marj",
      "Al Marqab",
      "Al Wahat",
      "An Nuqat al Khams",
      "Az Zawiyah",
      "Benghazi",
      "Derna",
      "Ghat",
      "Misrata",
      "Murzuq",
      "Nalut",
      "Sabha",
      "Sirte",
      "Tripoli",
      "Wadi al Hayaa",
      "Wadi al Shatii",
      "Yafran-Jadu",
    ],
  },
  Liechtenstein: {
    isd: "+423",
    iso2: "LI",
    states: [
      "Balzers",
      "Eschen",
      "Gamprin",
      "Mauren",
      "Planken",
      "Ruggell",
      "Schaan",
      "Schellenberg",
      "Triesen",
      "Triesenberg",
      "Vaduz",
    ],
  },
  Lithuania: {
    isd: "+370",
    iso2: "LT",
    states: [
      "Alytus",
      "Kaunas",
      "Klaipėda",
      "Marijampolė",
      "Panevėžys",
      "Šiauliai",
      "Tauragė",
      "Telšiai",
      "Utena",
      "Vilnius",
    ],
  },
  Luxembourg: {
    isd: "+352",
    iso2: "LU",
    states: [
      "Capellen",
      "Clervaux",
      "Diekirch",
      "Echternach",
      "Esch-sur-Alzette",
      "Grevenmacher",
      "Luxembourg",
      "Mersch",
      "Redange",
      "Remich",
      "Vianden",
      "Wiltz",
    ],
  },
  Madagascar: {
    isd: "+261",
    iso2: "MG",
    states: [
      "Alaotra-Mangoro",
      "Amoron'i Mania",
      "Analamanga",
      "Analanjirofo",
      "Androy",
      "Anosy",
      "Atsimo-Andrefana",
      "Atsimo-Atsinanana",
      "Atsinanana",
      "Betsiboka",
      "Boeny",
      "Bongolava",
      "Diana",
      "Haute Matsiatra",
      "Ihorombe",
      "Itasy",
      "Melaky",
      "Menabe",
      "SAVA",
      "Sofia",
      "Vakinankaratra",
      "Vatovavy-Fitovinany",
    ],
  },
  Malawi: {
    isd: "+265",
    iso2: "MW",
    states: [
      "Balaka",
      "Blantyre",
      "Chikwawa",
      "Chiradzulu",
      "Chitipa",
      "Dedza",
      "Dowa",
      "Karonga",
      "Kasungu",
      "Likoma",
      "Lilongwe",
      "Machinga",
      "Mangochi",
      "Mchinji",
      "Mulanje",
      "Mwanza",
      "Mzimba",
      "Neno",
      "Nkhata Bay",
      "Nkhotakota",
      "Nsanje",
      "Ntcheu",
      "Ntchisi",
      "Phalombe",
      "Rumphi",
      "Salima",
      "Thyolo",
      "Zomba",
    ],
  },
  Malaysia: {
    isd: "+60",
    iso2: "MY",
    states: [
      "Federal Territory of Kuala Lumpur",
      "Federal Territory of Labuan",
      "Federal Territory of Putrajaya",
      "Johor",
      "Kedah",
      "Kelantan",
      "Melaka",
      "Negeri Sembilan",
      "Pahang",
      "Penang",
      "Perak",
      "Perlis",
      "Sabah",
      "Sarawak",
      "Selangor",
      "Terengganu",
    ],
  },
  Maldives: {
    isd: "+960",
    iso2: "MV",
    states: [
      "Addu City",
      "Central Province",
      "Male",
      "North Central Province",
      "North Province",
      "South Central Province",
      "South Province",
      "Upper North Province",
      "Upper South Province",
    ],
  },
  Mali: {
    isd: "+223",
    iso2: "ML",
    states: [
      "Bamako",
      "Gao",
      "Kayes",
      "Kidal",
      "Koulikoro",
      "Ménaka",
      "Mopti",
      "Ségou",
      "Sikasso",
      "Taoudénit",
      "Tombouctou",
    ],
  },
  Malta: {
    isd: "+356",
    iso2: "MT",
    states: [
      "Attard",
      "Balzan",
      "Birgu",
      "Birkirkara",
      "Birzebbuga",
      "Bormla",
      "Dingli",
      "Fgura",
      "Floriana",
      "Fontana",
      "Ghajnsielem",
      "Gharb",
      "Gharghur",
      "Ghasri",
      "Ghaxaq",
      "Gudja",
      "Gzira",
      "Hamrun",
      "Iklin",
      "Imdina",
      "Imgarr",
      "Imqabba",
      "Imsida",
      "Imtarfa",
      "Isla",
      "Kalkara",
      "Kercem",
      "Kirkop",
      "Lija",
      "Luqa",
      "Marsa",
      "Marsaskala",
      "Marsaxlokk",
      "Mellieha",
      "Mosta",
      "Munxar",
      "Nadur",
      "Naxxar",
      "Paola",
      "Pembroke",
      "Pieta",
      "Qala",
      "Qormi",
      "Qrendi",
      "Rabat",
      "Rabat (Gozo)",
      "Safi",
      "San Gwann",
      "San Lawrence",
      "San Pawl il-Bahar",
      "Sannat",
      "Santa Lucija",
      "Santa Venera",
      "Siggiewi",
      "Sliema",
      "Swieqi",
      "Ta' Xbiex",
      "Tarxien",
      "Valletta",
      "Victoria",
      "Vittoriosa",
      "Xaghra",
      "Xewkija",
      "Xghajra",
      "Zabbar",
      "Zebbug",
      "Zebbug (Gozo)",
      "Zejtun",
      "Zurrieq",
    ],
  },
  "Marshall Islands": {
    isd: "+692",
    iso2: "MH",
    states: [
      "Ailinglaplap",
      "Ailuk",
      "Arno",
      "Aur",
      "Bikini & Kili",
      "Ebon",
      "Enewetak & Ujelang",
      "Jabat",
      "Jaluit",
      "Kwajalein",
      "Lae",
      "Lib",
      "Likiep",
      "Majuro",
      "Maloelap",
      "Mejit",
      "Mili",
      "Namorik",
      "Namu",
      "Rongelap",
      "Ujae",
      "Utrik",
      "Wotho",
      "Wotje",
    ],
  },
  Mauritania: {
    isd: "+222",
    iso2: "MR",
    states: [
      "Adrar",
      "Assaba",
      "Brakna",
      "Dakhlet Nouadhibou",
      "Gorgol",
      "Guidimaka",
      "Hodh Ech Chargui",
      "Hodh El Gharbi",
      "Inchiri",
      "Néma",
      "Nouakchott Nord",
      "Nouakchott Ouest",
      "Nouakchott Sud",
      "Tagant",
      "Tiris Zemmour",
      "Trarza",
    ],
  },
  Mauritius: {
    isd: "+230",
    iso2: "MU",
    states: [
      "Black River",
      "Flacq",
      "Grand Port",
      "Moka",
      "Pamplemousses",
      "Plaines Wilhems",
      "Port Louis",
      "Rivière du Rempart",
      "Rivière Noire",
      "Rodrigues",
      "Savanne",
    ],
  },
  Mexico: {
    isd: "+52",
    iso2: "MX",
    states: [
      "Aguascalientes",
      "Baja California",
      "Baja California Sur",
      "Campeche",
      "Chiapas",
      "Chihuahua",
      "Coahuila",
      "Colima",
      "Durango",
      "Guanajuato",
      "Guerrero",
      "Hidalgo",
      "Jalisco",
      "México",
      "Michoacán",
      "Morelos",
      "Nayarit",
      "Nuevo León",
      "Oaxaca",
      "Puebla",
      "Querétaro",
      "Quintana Roo",
      "San Luis Potosí",
      "Sinaloa",
      "Sonora",
      "Tabasco",
      "Tamaulipas",
      "Tlaxcala",
      "Veracruz",
      "Yucatán",
      "Zacatecas",
      "Mexico City",
    ],
  },
  Micronesia: {
    isd: "+691",
    iso2: "FM",
    states: ["Chuuk", "Kosrae", "Pohnpei", "Yap"],
  },
  Moldova: {
    isd: "+373",
    iso2: "MD",
    states: [
      "Anenii Noi",
      "Basarabeasca",
      "Briceni",
      "Cahul",
      "Călărași",
      "Căușeni",
      "Cimișlia",
      "Criuleni",
      "Dondușeni",
      "Drochia",
      "Dubăsari",
      "Edineț",
      "Fălești",
      "Florești",
      "Glodeni",
      "Hîncești",
      "Ialoveni",
      "Leova",
      "Nisporeni",
      "Ocnița",
      "Orhei",
      "Rezina",
      "Rîșcani",
      "Sîngerei",
      "Soroca",
      "Strășeni",
      "Șoldănești",
      "Ștefan Vodă",
      "Taraclia",
      "Telenești",
      "Ungheni",
      "Chișinău",
      "Bălți",
      "Găgăuzia",
      "Stânga Nistrului",
    ],
  },
  Monaco: {
    isd: "+377",
    iso2: "MC",
    states: [
      "Fontvieille",
      "La Condamine",
      "Monaco-Ville",
      "Monte Carlo",
      "Moneghetti",
    ],
  },
  Mongolia: {
    isd: "+976",
    iso2: "MN",
    states: [
      "Arkhangai",
      "Bayan-Ölgii",
      "Bayankhongor",
      "Bulgan",
      "Darkhan-Uul",
      "Dornod",
      "Dornogovi",
      "Dundgovi",
      "Govi-Altai",
      "Govisümber",
      "Khentii",
      "Khövsgöl",
      "Khovd",
      "Orkhon",
      "Övörkhangai",
      "Selenge",
      "Sükhbaatar",
      "Töv",
      "Ulaanbaatar",
      "Uvs",
      "Zavkhan",
    ],
  },
  Montenegro: {
    isd: "+382",
    iso2: "ME",
    states: [
      "Andrijevica",
      "Bar",
      "Berane",
      "Bijelo Polje",
      "Budva",
      "Cetinje",
      "Danilovgrad",
      "Gusinje",
      "Herceg Novi",
      "Kolašin",
      "Kotor",
      "Mojkovac",
      "Nikšić",
      "Petnjica",
      "Plav",
      "Pljevlja",
      "Plužine",
      "Podgorica",
      "Rožaje",
      "Šavnik",
      "Tivat",
      "Tuzi",
      "Ulcinj",
      "Žabljak",
    ],
  },
  Morocco: {
    isd: "+212",
    iso2: "MA",
    states: [
      "Béni Mellal-Khénifra",
      "Casablanca-Settat",
      "Drâa-Tafilalet",
      "Fès-Meknès",
      "Guelmim-Oued Noun",
      "Laâyoune-Sakia El Hamra",
      "Marrakesh-Safi",
      "Oriental",
      "Rabat-Salé-Kénitra",
      "Souss-Massa",
      "Tanger-Tetouan-Al Hoceima",
    ],
  },
  Mozambique: {
    isd: "+258",
    iso2: "MZ",
    states: [
      "Cabo Delgado",
      "Gaza",
      "Inhambane",
      "Manica",
      "Maputo",
      "Maputo City",
      "Nampula",
      "Niassa",
      "Sofala",
      "Tete",
      "Zambezia",
    ],
  },
  Myanmar: {
    isd: "+95",
    iso2: "MM",
    states: [
      "Ayeyarwady",
      "Bago",
      "Chin",
      "Kachin",
      "Kayah",
      "Kayin",
      "Magway",
      "Mandalay",
      "Mon",
      "Naypyidaw",
      "Rakhine",
      "Sagaing",
      "Shan",
      "Tanintharyi",
      "Yangon",
    ],
  },
  Namibia: {
    isd: "+264",
    iso2: "NA",
    states: [
      "//Karas",
      "Erongo",
      "Hardap",
      "Kavango East",
      "Kavango West",
      "Khomas",
      "Kunene",
      "Ohangwena",
      "Omaheke",
      "Omusati",
      "Oshana",
      "Oshikoto",
      "Otjozondjupa",
      "Sambiu",
      "Zambezi",
    ],
  },
  Nepal: {
    isd: "+977",
    iso2: "NP",
    states: [
      "Bagmati",
      "Gandaki",
      "Karnali",
      "Lumbini",
      "Madhesh",
      "Province No. 1",
      "Sudurpashchim",
    ],
  },
  Netherlands: {
    isd: "+31",
    iso2: "NL",
    states: [
      "Drenthe",
      "Flevoland",
      "Friesland",
      "Gelderland",
      "Groningen",
      "Limburg",
      "North Brabant",
      "North Holland",
      "Overijssel",
      "South Holland",
      "Utrecht",
      "Zeeland",
    ],
  },
  "New Zealand": {
    isd: "+64",
    iso2: "NZ",
    states: [
      "Auckland",
      "Bay of Plenty",
      "Canterbury",
      "Gisborne",
      "Hawke's Bay",
      "Manawatu-Whanganui",
      "Marlborough",
      "Nelson",
      "Northland",
      "Otago",
      "Southland",
      "Taranaki",
      "Tasman",
      "Waikato",
      "Wellington",
      "West Coast",
    ],
  },
  Nicaragua: {
    isd: "+505",
    iso2: "NI",
    states: [
      "Boaco",
      "Carazo",
      "Chinandega",
      "Chontales",
      "Estelí",
      "Granada",
      "Jinotega",
      "León",
      "Madriz",
      "Managua",
      "Masaya",
      "Matagalpa",
      "North Caribbean Coast",
      "Nueva Segovia",
      "Río San Juan",
      "Rivas",
      "South Caribbean Coast",
    ],
  },
  Niger: {
    isd: "+227",
    iso2: "NE",
    states: [
      "Agadez",
      "Dosso",
      "Maradi",
      "Niamey",
      "Tahoua",
      "Tillabéri",
      "Zinder",
    ],
  },
  Nigeria: {
    isd: "+234",
    iso2: "NG",
    states: [
      "Abia",
      "Adamawa",
      "Akwa Ibom",
      "Anambra",
      "Bauchi",
      "Bayelsa",
      "Benue",
      "Borno",
      "Cross River",
      "Delta",
      "Ebonyi",
      "Edo",
      "Ekiti",
      "Enugu",
      "FCT",
      "Gombe",
      "Imo",
      "Jigawa",
      "Kaduna",
      "Kano",
      "Katsina",
      "Kebbi",
      "Kogi",
      "Kwara",
      "Lagos",
      "Nasarawa",
      "Niger",
      "Ogun",
      "Ondo",
      "Osun",
      "Oyo",
      "Plateau",
      "Rivers",
      "Sokoto",
      "Taraba",
      "Yobe",
      "Zamfara",
    ],
  },
  "North Macedonia": {
    isd: "+389",
    iso2: "MK",
    states: [
      "Aerodrom",
      "Aračinovo",
      "Berovo",
      "Bitola",
      "Bogdanci",
      "Bogovinje",
      "Bosilovo",
      "Brvenica",
      "Butel",
      "Čair",
      "Čaška",
      "Centar",
      "Centar Župa",
      "Češinovo-Obleševo",
      "Čučer-Sandevo",
      "Debar",
      "Debarca",
      "Delčevo",
      "Demir Hisar",
      "Demir Kapija",
      "Dojran",
      "Dolneni",
      "Drugovo",
      "Gazi Baba",
      "Gevgelija",
      "Gjorče Petrov",
      "Gostivar",
      "Grad Skopje",
      "Gradsko",
      "Ilinden",
      "Jegunovce",
      "Karbinci",
      "Karpoš",
      "Kavadarci",
      "Kičevo",
      "Kisela Voda",
      "Kočani",
      "Konče",
      "Kratovo",
      "Kriva Palanka",
      "Krivogaštani",
      "Kruševo",
      "Kumanovo",
      "Lipkovo",
      "Lozovo",
      "Makedonska Kamenica",
      "Makedonski Brod",
      "Mavrovo i Rostuša",
      "Mogila",
      "Negotino",
      "Novaci",
      "Novo Selo",
      "Ohrid",
      "Petrovec",
      "Plasnica",
      "Prilep",
      "Probištip",
      "Radoviš",
      "Rankovce",
      "Resen",
      "Rosoman",
      "Saraj",
      "Sopište",
      "Staro Nagoričane",
      "Štip",
      "Struga",
      "Strumica",
      "Studeničani",
      "Šuto Orizari",
      "Sveti Nikole",
      "Tearce",
      "Tetovo",
      "Valandovo",
      "Vasilevo",
      "Veles",
      "Vevčani",
      "Vinica",
      "Vranestica",
      "Vrapciste",
      "Zelenikovo",
      "Zelino",
      "Zrnovci",
    ],
  },
  Norway: {
    isd: "+47",
    iso2: "NO",
    states: [
      "Agder",
      "Innlandet",
      "Møre og Romsdal",
      "Nordland",
      "Oslo",
      "Rogaland",
      "Troms og Finnmark",
      "Trøndelag",
      "Vestfold og Telemark",
      "Vestland",
      "Viken",
    ],
  },
  Oman: {
    isd: "+968",
    iso2: "OM",
    states: [
      "Ad Dakhiliyah",
      "Al Batinah North",
      "Al Batinah South",
      "Al Buraimi",
      "Al Wusta",
      "Ash Sharqiyah North",
      "Ash Sharqiyah South",
      "Dhofar",
      "Musandam",
      "Muscat",
    ],
  },
  Pakistan: {
    isd: "+92",
    iso2: "PK",
    states: [
      "Azad Kashmir",
      "Balochistan",
      "Gilgit-Baltistan",
      "Islamabad Capital Territory",
      "Khyber Pakhtunkhwa",
      "Punjab",
      "Sindh",
    ],
  },
  Palau: {
    isd: "+680",
    iso2: "PW",
    states: [
      "Aimeliik",
      "Airai",
      "Angaur",
      "Hatohobei",
      "Kayangel",
      "Koror",
      "Melekeok",
      "Ngaraard",
      "Ngarchelong",
      "Ngardmau",
      "Ngatpang",
      "Ngchesar",
      "Ngeremlengui",
      "Ngiwal",
      "Peleliu",
      "Sonsorol",
    ],
  },
  Panama: {
    isd: "+507",
    iso2: "PA",
    states: [
      "Bocas del Toro",
      "Chiriquí",
      "Coclé",
      "Colón",
      "Darién",
      "Emberá",
      "Herrera",
      "Kuna Yala",
      "Los Santos",
      "Ngöbe-Buglé",
      "Panamá",
      "Panamá Oeste",
      "Veraguas",
      "Wounaan",
    ],
  },
  "Papua New Guinea": {
    isd: "+675",
    iso2: "PG",
    states: [
      "Bougainville",
      "Central",
      "Chimbu",
      "East New Britain",
      "East Sepik",
      "Eastern Highlands",
      "Enga",
      "Gulf",
      "Hela",
      "Jiwaka",
      "Madang",
      "Manus",
      "Milne Bay",
      "Morobe",
      "National Capital",
      "New Ireland",
      "Northern",
      "Southern Highlands",
      "West New Britain",
      "West Sepik",
      "Western",
      "Western Highlands",
    ],
  },
  Paraguay: {
    isd: "+595",
    iso2: "PY",
    states: [
      "Alto Paraguay",
      "Alto Paraná",
      "Amambay",
      "Asunción",
      "Boquerón",
      "Caaguazú",
      "Caazapá",
      "Canindeyu",
      "Central",
      "Concepción",
      "Cordillera",
      "Guairá",
      "Itapúa",
      "Misiones",
      "Ñeembucú",
      "Paraguarí",
      "Presidente Hayes",
      "San Pedro",
    ],
  },
  Peru: {
    isd: "+51",
    iso2: "PE",
    states: [
      "Amazonas",
      "Ancash",
      "Apurímac",
      "Arequipa",
      "Ayacucho",
      "Cajamarca",
      "Callao",
      "Cusco",
      "Huancavelica",
      "Huánuco",
      "Ica",
      "Junín",
      "La Libertad",
      "Lambayeque",
      "Lima",
      "Loreto",
      "Madre de Dios",
      "Moquegua",
      "Pasco",
      "Piura",
      "Puno",
      "San Martín",
      "Tacna",
      "Tumbes",
      "Ucayali",
    ],
  },
  Philippines: {
    isd: "+63",
    iso2: "PH",
    states: [
      "Abra",
      "Agusan del Norte",
      "Agusan del Sur",
      "Aklan",
      "Albay",
      "Antique",
      "Apayao",
      "Aurora",
      "Basilan",
      "Bataan",
      "Batanes",
      "Batangas",
      "Benguet",
      "Biliran",
      "Bohol",
      "Bukidnon",
      "Bulacan",
      "Cagayan",
      "Camarines Norte",
      "Camarines Sur",
      "Camiguin",
      "Capiz",
      "Catanduanes",
      "Cavite",
      "Cebu",
      "Compostela Valley",
      "Cotabato",
      "Davao de Oro",
      "Davao del Norte",
      "Davao del Sur",
      "Davao Occidental",
      "Davao Oriental",
      "Dinagat Islands",
      "Eastern Samar",
      "Guimaras",
      "Ifugao",
      "Ilocos Norte",
      "Ilocos Sur",
      "Iloilo",
      "Isabela",
      "Kalinga",
      "La Union",
      "Laguna",
      "Lanao del Norte",
      "Lanao del Sur",
      "Leyte",
      "Maguindanao",
      "Marinduque",
      "Masbate",
      "Metro Manila",
      "Misamis Occidental",
      "Misamis Oriental",
      "Mountain Province",
      "Negros Occidental",
      "Negros Oriental",
      "Northern Samar",
      "Nueva Ecija",
      "Nueva Vizcaya",
      "Occidental Mindoro",
      "Oriental Mindoro",
      "Palawan",
      "Pampanga",
      "Pangasinan",
      "Quezon",
      "Quirino",
      "Rizal",
      "Romblon",
      "Samar",
      "Sarangani",
      "Siquijor",
      "Sorsogon",
      "South Cotabato",
      "Southern Leyte",
      "Sultan Kudarat",
      "Sulu",
      "Surigao del Norte",
      "Surigao del Sur",
      "Tarlac",
      "Tawi-Tawi",
      "Zambales",
      "Zamboanga del Norte",
      "Zamboanga del Sur",
      "Zamboanga Sibugay",
    ],
  },
  Poland: {
    isd: "+48",
    iso2: "PL",
    states: [
      "Greater Poland",
      "Holy Cross",
      "Kuyavian-Pomeranian",
      "Lesser Poland",
      "Lodz",
      "Lower Silesian",
      "Lublin",
      "Lubusz",
      "Masovian",
      "Opole",
      "Podlaskie",
      "Pomeranian",
      "Silesian",
      "Subcarpathian",
      "Warmian-Masurian",
      "West Pomeranian",
    ],
  },
  Portugal: {
    isd: "+351",
    iso2: "PT",
    states: [
      "Aveiro",
      "Azores",
      "Beja",
      "Braga",
      "Bragança",
      "Castelo Branco",
      "Coimbra",
      "Évora",
      "Faro",
      "Guarda",
      "Leiria",
      "Lisbon",
      "Madeira",
      "Portalegre",
      "Porto",
      "Santarém",
      "Setúbal",
      "Viana do Castelo",
      "Vila Real",
      "Viseu",
    ],
  },
  Qatar: {
    isd: "+974",
    iso2: "QA",
    states: [
      "Ad Dawhah",
      "Al Khor",
      "Al Rayyan",
      "Al Wakrah",
      "Al-Shahaniya",
      "Madinat ash Shamal",
      "Umm Salal",
      "Al Daayen",
    ],
  },
  Romania: {
    isd: "+40",
    iso2: "RO",
    states: [
      "Alba",
      "Arad",
      "Argeș",
      "Bacău",
      "Bihor",
      "Bistrița-Năsăud",
      "Botoșani",
      "Brăila",
      "Brașov",
      "Bucharest",
      "Buzău",
      "Călărași",
      "Caraș-Severin",
      "Cluj",
      "Constanța",
      "Covasna",
      "Dâmbovița",
      "Dolj",
      "Galați",
      "Giurgiu",
      "Gorj",
      "Harghita",
      "Hunedoara",
      "Ialomița",
      "Iași",
      "Ilfov",
      "Maramureș",
      "Mehedinți",
      "Mureș",
      "Neamț",
      "Olt",
      "Prahova",
      "Sălaj",
      "Satu Mare",
      "Sibiu",
      "Suceava",
      "Teleorman",
      "Timis",
      "Tulcea",
      "Vâlcea",
      "Vaslui",
      "Vrancea",
    ],
  },
  Russia: {
    isd: "+7",
    iso2: "RU",
    states: [
      "Adygea",
      "Altai Krai",
      "Altai Republic",
      "Amur",
      "Arkhangelsk",
      "Astrakhan",
      "Bashkortostan",
      "Belgorod",
      "Bryansk",
      "Buryatia",
      "Chechnya",
      "Chelyabinsk",
      "Chukotka",
      "Chuvashia",
      "Dagestan",
      "Ingushetia",
      "Irkutsk",
      "Ivanovo",
      "Jewish Autonomous Oblast",
      "Kabardino-Balkaria",
      "Kaliningrad",
      "Kalmykia",
      "Kaluga",
      "Kamchatka",
      "Karachay-Cherkessia",
      "Karelia",
      "Kemerovo",
      "Khabarovsk",
      "Khakassia",
      "Khanty-Mansiysk",
      "Kirov",
      "Komi",
      "Kostroma",
      "Krasnodar",
      "Krasnoyarsk",
      "Kurgan",
      "Kursk",
      "Leningrad",
      "Lipetsk",
      "Magadan",
      "Mari El",
      "Mordovia",
      "Moscow",
      "Moscow Oblast",
      "Murmansk",
      "Nenets",
      "Nizhny Novgorod",
      "North Ossetia",
      "Novgorod",
      "Novosibirsk",
      "Omsk",
      "Orel",
      "Orenburg",
      "Penza",
      "Perm",
      "Primorsky Krai",
      "Pskov",
      "Rostov",
      "Ryazan",
      "Sakha",
      "Sakhalin",
      "Samara",
      "Saratov",
      "Smolensk",
      "St. Petersburg",
      "Stavropol",
      "Sverdlovsk",
      "Tambov",
      "Tatarstan",
      "Tomsk",
      "Tula",
      "Tuva",
      "Tver",
      "Tyumen",
      "Udmurtia",
      "Ulyanovsk",
      "Vladimir",
      "Volgograd",
      "Vologda",
      "Voronezh",
      "Yamalo-Nenets",
      "Yaroslavl",
      "Zabaykalsky Krai",
    ],
  },
  Rwanda: {
    isd: "+250",
    iso2: "RW",
    states: ["Eastern", "Kigali", "Northern", "Southern", "Western"],
  },
  "Saint Kitts and Nevis": {
    isd: "+1-869",
    iso2: "KN",
    states: [
      "Christ Church Nichola Town",
      "Nevis",
      "Saint Anne Sandy Point",
      "Saint George Basseterre",
      "Saint George Gingerland",
      "Saint James Windward",
      "Saint John Capesterre",
      "Saint John Figtree",
      "Saint Mary Cayon",
      "Saint Paul Capesterre",
      "Saint Paul Charlestown",
      "Saint Peter Basseterre",
      "Saint Thomas Lowland",
      "Saint Thomas Middle Island",
      "Trinity Palmetto Point",
    ],
  },
  "Saint Lucia": {
    isd: "+1-758",
    iso2: "LC",
    states: [
      "Anse la Raye",
      "Canaries",
      "Castries",
      "Choiseul",
      "Dennery",
      "Gros Islet",
      "Laborie",
      "Micoud",
      "Soufrière",
      "Vieux Fort",
    ],
  },
  "Saint Vincent and the Grenadines": {
    isd: "+1-784",
    iso2: "VC",
    states: [
      "Charlotte",
      "Grenadines",
      "Saint Andrew",
      "Saint David",
      "Saint George",
      "Saint Patrick",
    ],
  },
  Samoa: {
    isd: "+685",
    iso2: "WS",
    states: [
      "Aiga-i-le-Tai",
      "Atua",
      "Fa'asaleleaga",
      "Gaga'emauga",
      "Gagaifomauga",
      "Palauli",
      "Satupa'itea",
      "Tuamasaga",
      "Va'a-o-Fonoti",
      "Vaisigano",
    ],
  },
  "San Marino": {
    isd: "+378",
    iso2: "SM",
    states: [
      "Acquaviva",
      "Borgo Maggiore",
      "Chiesanuova",
      "Domagnano",
      "Faetano",
      "Fiorentino",
      "Montegiardino",
      "San Marino",
      "Serravalle",
    ],
  },
  "Saudi Arabia": {
    isd: "+966",
    iso2: "SA",
    states: [
      "Al Bahah",
      "Al Jawf",
      "Al Madinah",
      "Al Qasim",
      "Asir",
      "Eastern Province",
      "Ha'il",
      "Jazan",
      "Mecca",
      "Najran",
      "Northern Borders",
      "Riyadh",
      "Tabuk",
    ],
  },
  Senegal: {
    isd: "+221",
    iso2: "SN",
    states: [
      "Dakar",
      "Diourbel",
      "Fatick",
      "Kaffrine",
      "Kaolack",
      "Kédougou",
      "Kolda",
      "Louga",
      "Matam",
      "Saint-Louis",
      "Sédhiou",
      "Tambacounda",
      "Thiès",
      "Ziguinchor",
    ],
  },
  Serbia: {
    isd: "+381",
    iso2: "RS",
    states: [
      "Belgrade",
      "Bor",
      "Braničevo",
      "Jablanica",
      "Kolubara",
      "Mačva",
      "Moravica",
      "Nišava",
      "Pčinja",
      "Pirot",
      "Podunavlje",
      "Pomoravlje",
      "Rasina",
      "Raška",
      "South Banat",
      "South Bačka",
      "Srem",
      "Šumadija",
      "Toplica",
      "Vojvodina",
      "Zaječar",
      "Zlatibor",
      "North Banat",
      "North Bačka",
      "West Bačka",
      "Kosovo and Metohija",
    ],
  },
  "Sierra Leone": {
    isd: "+232",
    iso2: "SL",
    states: ["Eastern", "Northern", "North West", "Southern", "Western Area"],
  },
  Singapore: {
    isd: "+65",
    iso2: "SG",
    states: [
      "Central Singapore",
      "North East",
      "North West",
      "South East",
      "South West",
    ],
  },
  Slovakia: {
    isd: "+421",
    iso2: "SK",
    states: [
      "Banská Bystrica",
      "Bratislava",
      "Košice",
      "Nitra",
      "Prešov",
      "Trenčín",
      "Trnava",
      "Žilina",
    ],
  },
  Slovenia: {
    isd: "+386",
    iso2: "SI",
    states: [
      "Central Slovenia",
      "Coastal-Karst",
      "Gorenjska",
      "Gorizia",
      "Inner Carniola-Karst",
      "Littoral-Inner Carniola",
      "Lower Sava",
      "Mura",
      "Savinja",
      "Southeast Slovenia",
      "Spodnja Savinjska",
      "Upper Carniola",
      "Zasavje",
    ],
  },
  Somalia: {
    isd: "+252",
    iso2: "SO",
    states: [
      "Awdal",
      "Bakool",
      "Banaadir",
      "Bari",
      "Bay",
      "Galguduud",
      "Gedo",
      "Hiiraan",
      "Jubbada Dhexe",
      "Jubbada Hoose",
      "Lower Juba",
      "Lower Shabelle",
      "Mudug",
      "Nugaal",
      "Sanaag",
      "Shabeellaha Dhexe",
      "Shabeellaha Hoose",
      "Sool",
      "Togdheer",
      "Woqooyi Galbeed",
    ],
  },
  "South Africa": {
    isd: "+27",
    iso2: "ZA",
    states: [
      "Eastern Cape",
      "Free State",
      "Gauteng",
      "KwaZulu-Natal",
      "Limpopo",
      "Mpumalanga",
      "North West",
      "Northern Cape",
      "Western Cape",
    ],
  },
  "South Korea": {
    isd: "+82",
    iso2: "KR",
    states: [
      "Busan",
      "Chungcheongbuk-do",
      "Chungcheongnam-do",
      "Daegu",
      "Daejeon",
      "Gangwon-do",
      "Gwangju",
      "Gyeonggi-do",
      "Gyeongsangbuk-do",
      "Gyeongsangnam-do",
      "Incheon",
      "Jeju-do",
      "Jeollabuk-do",
      "Jeollanam-do",
      "North Chungcheong",
      "North Gyeongsang",
      "North Jeolla",
      "Seoul",
      "Sejong",
      "South Chungcheong",
      "South Gyeongsang",
      "South Jeolla",
      "Ulsan",
    ],
  },
  "South Sudan": {
    isd: "+211",
    iso2: "SS",
    states: [
      "Central Equatoria",
      "Eastern Equatoria",
      "Jonglei",
      "Lakes",
      "Northern Bahr el Ghazal",
      "Unity",
      "Upper Nile",
      "Warrap",
      "Western Bahr el Ghazal",
      "Western Equatoria",
    ],
  },
  Spain: {
    isd: "+34",
    iso2: "ES",
    states: [
      "Andalusia",
      "Aragon",
      "Asturias",
      "Balearic Islands",
      "Basque Country",
      "Canary Islands",
      "Cantabria",
      "Castile and León",
      "Castilla–La Mancha",
      "Catalonia",
      "Ceuta",
      "Extremadura",
      "Galicia",
      "La Rioja",
      "Madrid",
      "Melilla",
      "Murcia",
      "Navarre",
      "Valencia",
    ],
  },
  "Sri Lanka": {
    isd: "+94",
    iso2: "LK",
    states: [
      "Central",
      "Eastern",
      "Northern",
      "North Central",
      "North Western",
      "Sabaragamuwa",
      "Southern",
      "Uva",
      "Western",
    ],
  },
  Sudan: {
    isd: "+249",
    iso2: "SD",
    states: [
      "Al Qadarif",
      "Blue Nile",
      "Central Darfur",
      "East Darfur",
      "Kassala",
      "Khartoum",
      "North Darfur",
      "North Kordofan",
      "Northern",
      "Red Sea",
      "River Nile",
      "Sennar",
      "South Darfur",
      "South Kordofan",
      "West Darfur",
      "West Kordofan",
      "White Nile",
    ],
  },
  Suriname: {
    isd: "+597",
    iso2: "SR",
    states: [
      "Brokopondo",
      "Commewijne",
      "Coronie",
      "Marowijne",
      "Nickerie",
      "Para",
      "Paramaribo",
      "Saramacca",
      "Sipaliwini",
      "Wanica",
    ],
  },
  Sweden: {
    isd: "+46",
    iso2: "SE",
    states: [
      "Blekinge",
      "Dalarna",
      "Gävleborg",
      "Gotland",
      "Halland",
      "Jämtland",
      "Jönköping",
      "Kalmar",
      "Kronoberg",
      "Norrbotten",
      "Örebro",
      "Östergötland",
      "Skåne",
      "Södermanland",
      "Stockholm",
      "Uppsala",
      "Värmland",
      "Västerbotten",
      "Västernorrland",
      "Västmanland",
      "Västra Götaland",
    ],
  },
  Switzerland: {
    isd: "+41",
    iso2: "CH",
    states: [
      "Aargau",
      "Appenzell Ausserrhoden",
      "Appenzell Innerrhoden",
      "Basel-Landschaft",
      "Basel-Stadt",
      "Bern",
      "Fribourg",
      "Geneva",
      "Glarus",
      "Graubünden",
      "Jura",
      "Lucerne",
      "Neuchâtel",
      "Nidwalden",
      "Obwalden",
      "Schaffhausen",
      "Schwyz",
      "Solothurn",
      "St. Gallen",
      "Thurgau",
      "Ticino",
      "Uri",
      "Valais",
      "Vaud",
      "Zug",
      "Zürich",
    ],
  },
  Syria: {
    isd: "+963",
    iso2: "SY",
    states: [
      "Al-Hasakah",
      "Al-Raqqah",
      "Aleppo",
      "As-Suwayda",
      "Damascus",
      "Daraa",
      "Deir ez-Zor",
      "Hama",
      "Homs",
      "Idlib",
      "Latakia",
      "Quneitra",
      "Rif Dimashq",
      "Tartus",
    ],
  },
  Taiwan: {
    isd: "+886",
    iso2: "TW",
    states: [
      "Changhua",
      "Chiayi",
      "Chiayi City",
      "Hualien",
      "Hsinchu",
      "Hsinchu City",
      "Kaohsiung",
      "Keelung",
      "Kinmen",
      "Lienchiang",
      "Miaoli",
      "Nantou",
      "New Taipei",
      "Penghu",
      "Pingtung",
      "Taichung",
      "Tainan",
      "Taipei",
      "Taitung",
      "Taoyuan",
      "Yilan",
      "Yunlin",
    ],
  },
  Tajikistan: {
    isd: "+992",
    iso2: "TJ",
    states: [
      "Districts of Republican Subordination",
      "Gorno-Badakhshan",
      "Khatlon",
      "Sughd",
    ],
  },
  Tanzania: {
    isd: "+255",
    iso2: "TZ",
    states: [
      "Arusha",
      "Dar es Salaam",
      "Dodoma",
      "Geita",
      "Iringa",
      "Kagera",
      "Katavi",
      "Kigoma",
      "Kilimanjaro",
      "Lindi",
      "Manyara",
      "Mara",
      "Mbeya",
      "Morogoro",
      "Mtwara",
      "Mwanza",
      "Njombe",
      "Pemba North",
      "Pemba South",
      "Pwani",
      "Rukwa",
      "Ruvuma",
      "Shinyanga",
      "Simiyu",
      "Singida",
      "Songwe",
      "Tabora",
      "Tanga",
      "Zanzibar Central/South",
      "Zanzibar North",
      "Zanzibar Urban/West",
    ],
  },
  Thailand: {
    isd: "+66",
    iso2: "TH",
    states: [
      "Amnat Charoen",
      "Ang Thong",
      "Bangkok",
      "Bueng Kan",
      "Buri Ram",
      "Chachoengsao",
      "Chai Nat",
      "Chaiyaphum",
      "Chanthaburi",
      "Chiang Mai",
      "Chiang Rai",
      "Chon Buri",
      "Chumphon",
      "Kalasin",
      "Kamphaeng Phet",
      "Kanchanaburi",
      "Khon Kaen",
      "Krabi",
      "Lampang",
      "Lamphun",
      "Loei",
      "Lop Buri",
      "Mae Hong Son",
      "Maha Sarakham",
      "Mukdahan",
      "Nakhon Nayok",
      "Nakhon Pathom",
      "Nakhon Phanom",
      "Nakhon Ratchasima",
      "Nakhon Sawan",
      "Nakhon Si Thammarat",
      "Nan",
      "Narathiwat",
      "Nong Bua Lam Phu",
      "Nong Khai",
      "Nonthaburi",
      "Pathum Thani",
      "Pattani",
      "Phang Nga",
      "Phatthalung",
      "Phayao",
      "Phetchabun",
      "Phetchaburi",
      "Phichit",
      "Phitsanulok",
      "Phra Nakhon Si Ayutthaya",
      "Phrae",
      "Phuket",
      "Prachin Buri",
      "Prachuap Khiri Khan",
      "Ranong",
      "Ratchaburi",
      "Rayong",
      "Roi Et",
      "Sa Kaeo",
      "Sakon Nakhon",
      "Samut Prakan",
      "Samut Sakhon",
      "Samut Songkhram",
      "Saraburi",
      "Satun",
      "Si Sa Ket",
      "Sing Buri",
      "Songkhla",
      "Sukhothai",
      "Suphan Buri",
      "Surat Thani",
      "Surin",
      "Tak",
      "Trang",
      "Trat",
      "Ubon Ratchathani",
      "Udon Thani",
      "Uthai Thani",
      "Uttaradit",
      "Yala",
      "Yasothon",
    ],
  },
  "Timor-Leste": {
    isd: "+670",
    iso2: "TL",
    states: [
      "Aileu",
      "Ainaro",
      "Baucau",
      "Bobonaro",
      "Cova Lima",
      "Dili",
      "Ermera",
      "Lautem",
      "Liquiçá",
      "Manatuto",
      "Manufahi",
      "Oecusse",
      "Viqueque",
    ],
  },
  Togo: {
    isd: "+228",
    iso2: "TG",
    states: ["Centrale", "Kara", "Maritime", "Plateaux", "Savanes"],
  },
  Tonga: {
    isd: "+676",
    iso2: "TO",
    states: ["Eua", "Ha'apai", "Niuas", "Tongatapu", "Vava'u"],
  },
  "Trinidad and Tobago": {
    isd: "+1-868",
    iso2: "TT",
    states: [
      "Arima",
      "Chaguanas",
      "Couva-Tabaquite-Talparo",
      "Diego Martin",
      "Mayaro",
      "Penal-Debe",
      "Port of Spain",
      "Princes Town",
      "Rio Claro-Mayaro",
      "San Fernando",
      "San Juan-Laventille",
      "Sangre Grande",
      "Siparia",
      "Tobago",
      "Tunapuna-Piarco",
    ],
  },
  Tunisia: {
    isd: "+216",
    iso2: "TN",
    states: [
      "Ariana",
      "Beja",
      "Ben Arous",
      "Bizerte",
      "Gabes",
      "Gafsa",
      "Jendouba",
      "Kairouan",
      "Kasserine",
      "Kebili",
      "Kef",
      "Mahdia",
      "Manouba",
      "Medenine",
      "Monastir",
      "Nabeul",
      "Sfax",
      "Sidi Bouzid",
      "Siliana",
      "Sousse",
      "Tataouine",
      "Tozeur",
      "Tunis",
      "Zaghouan",
    ],
  },
  Turkey: {
    isd: "+90",
    iso2: "TR",
    states: [
      "Adana",
      "Adıyaman",
      "Afyonkarahisar",
      "Ağrı",
      "Aksaray",
      "Amasya",
      "Ankara",
      "Antalya",
      "Ardahan",
      "Artvin",
      "Aydın",
      "Balıkesir",
      "Bartın",
      "Batman",
      "Bayburt",
      "Bilecik",
      "Bingöl",
      "Bitlis",
      "Bolu",
      "Burdur",
      "Bursa",
      "Çanakkale",
      "Çankırı",
      "Çorum",
      "Denizli",
      "Diyarbakır",
      "Düzce",
      "Edirne",
      "Elazığ",
      "Erzincan",
      "Erzurum",
      "Eskişehir",
      "Gaziantep",
      "Giresun",
      "Gümüşhane",
      "Hakkari",
      "Hatay",
      "Iğdır",
      "Isparta",
      "İstanbul",
      "İzmir",
      "Kahramanmaraş",
      "Karabük",
      "Karaman",
      "Kars",
      "Kastamonu",
      "Kayseri",
      "Kilis",
      "Kırıkkale",
      "Kırklareli",
      "Kırşehir",
      "Kocaeli",
      "Konya",
      "Kütahya",
      "Malatya",
      "Manisa",
      "Mardin",
      "Mersin",
      "Muğla",
      "Muş",
      "Nevşehir",
      "Niğde",
      "Ordu",
      "Osmaniye",
      "Rize",
      "Sakarya",
      "Samsun",
      "Şanlıurfa",
      "Siirt",
      "Sinop",
      "Şırnak",
      "Sivas",
      "Tekirdağ",
      "Tokat",
      "Trabzon",
      "Tunceli",
      "Uşak",
      "Van",
      "Yalova",
      "Yozgat",
      "Zonguldak",
    ],
  },
  Turkmenistan: {
    isd: "+993",
    iso2: "TM",
    states: ["Ahal", "Ashgabat", "Balkan", "Daşoguz", "Lebap", "Mary"],
  },
  Tuvalu: {
    isd: "+688",
    iso2: "TV",
    states: [
      "Funafuti",
      "Nanumanga",
      "Nanumea",
      "Niutao",
      "Nui",
      "Nukufetau",
      "Nukulaelae",
      "Vaitupu",
    ],
  },
  Uganda: {
    isd: "+256",
    iso2: "UG",
    states: [
      "Abim",
      "Adjumani",
      "Agago",
      "Alebtong",
      "Amolatar",
      "Amudat",
      "Amuria",
      "Amuru",
      "Apac",
      "Arua",
      "Budaka",
      "Bududa",
      "Bugiri",
      "Buhweju",
      "Buikwe",
      "Bukedea",
      "Bukomansimbi",
      "Bukwa",
      "Bulambuli",
      "Buliisa",
      "Bundibugyo",
      "Bunyangabu",
      "Bushenyi",
      "Busia",
      "Butaleja",
      "Butebo",
      "Buyende",
      "Dokolo",
      "Gomba",
      "Gulu",
      "Hoima",
      "Ibanda",
      "Iganga",
      "Isingiro",
      "Jinja",
      "Kaabong",
      "Kabale",
      "Kabarole",
      "Kaberamaido",
      "Kagadi",
      "Kakumiro",
      "Kalaki",
      "Kalangala",
      "Kaliro",
      "Kalungu",
      "Kampala",
      "Kamuli",
      "Kamwenge",
      "Kanungu",
      "Kapchorwa",
      "Kapelebyong",
      "Karenga",
      "Kasanda",
      "Kasese",
      "Katakwi",
      "Kayunga",
      "Kazo",
      "Kibaale",
      "Kiboga",
      "Kibuku",
      "Kikuube",
      "Kiruhura",
      "Kiryandongo",
      "Kisoro",
      "Kitagwenda",
      "Kitgum",
      "Koboko",
      "Kole",
      "Kotido",
      "Kumi",
      "Kwania",
      "Kween",
      "Kyankwanzi",
      "Kyegegwa",
      "Kyenjojo",
      "Kyotera",
      "Lamwo",
      "Lira",
      "Luuka",
      "Luwero",
      "Lwengo",
      "Lyantonde",
      "Madi-Okollo",
      "Manafwa",
      "Maracha",
      "Masaka",
      "Masindi",
      "Mayuge",
      "Mbale",
      "Mbarara",
      "Mitooma",
      "Mityana",
      "Moroto",
      "Moyo",
      "Mpigi",
      "Mubende",
      "Mukono",
      "Nabilatuk",
      "Nakapiripirit",
      "Nakaseke",
      "Nakasongola",
      "Namayingo",
      "Namisindwa",
      "Namutumba",
      "Napak",
      "Nebbi",
      "Ngora",
      "Ntoroko",
      "Ntungamo",
      "Nwoya",
      "Obongi",
      "Omoro",
      "Otuke",
      "Oyam",
      "Pader",
      "Pakwach",
      "Pallisa",
      "Rakai",
      "Rubanda",
      "Rubirizi",
      "Rukiga",
      "Rukungiri",
      "Rwampara",
      "Sembabule",
      "Serere",
      "Sheema",
      "Sironko",
      "Soroti",
      "Tororo",
      "Wakiso",
      "Yumbe",
      "Zombo",
    ],
  },
  Ukraine: {
    isd: "+380",
    iso2: "UA",
    states: [
      "Cherkasy",
      "Chernihiv",
      "Chernivtsi",
      "Dnipropetrovsk",
      "Donetsk",
      "Ivano-Frankivsk",
      "Kharkiv",
      "Kherson",
      "Khmelnytskyi",
      "Kirovohrad",
      "Kyiv",
      "Kyiv City",
      "Luhansk",
      "Lviv",
      "Mykolaiv",
      "Odessa",
      "Poltava",
      "Rivne",
      "Sumy",
      "Ternopil",
      "Vinnytsia",
      "Volyn",
      "Zakarpattia",
      "Zaporizhzhia",
      "Zhytomyr",
    ],
  },
  "United Arab Emirates": {
    isd: "+971",
    iso2: "AE",
    states: [
      "Abu Dhabi",
      "Ajman",
      "Dubai",
      "Fujairah",
      "Ras Al Khaimah",
      "Sharjah",
      "Umm Al Quwain",
    ],
  },
  "United Kingdom": {
    isd: "+44",
    iso2: "GB",
    states: ["England", "Northern Ireland", "Scotland", "Wales"],
  },
  "United States": {
    isd: "+1",
    iso2: "US",
    states: [
      "Alabama",
      "Alaska",
      "Arizona",
      "Arkansas",
      "California",
      "Colorado",
      "Connecticut",
      "Delaware",
      "Florida",
      "Georgia",
      "Hawaii",
      "Idaho",
      "Illinois",
      "Indiana",
      "Iowa",
      "Kansas",
      "Kentucky",
      "Louisiana",
      "Maine",
      "Maryland",
      "Massachusetts",
      "Michigan",
      "Minnesota",
      "Mississippi",
      "Missouri",
      "Montana",
      "Nebraska",
      "Nevada",
      "New Hampshire",
      "New Jersey",
      "New Mexico",
      "New York",
      "North Carolina",
      "North Dakota",
      "Ohio",
      "Oklahoma",
      "Oregon",
      "Pennsylvania",
      "Rhode Island",
      "South Carolina",
      "South Dakota",
      "Tennessee",
      "Texas",
      "Utah",
      "Vermont",
      "Virginia",
      "Washington",
      "West Virginia",
      "Wisconsin",
      "Wyoming",
    ],
  },
  Uruguay: {
    isd: "+598",
    iso2: "UY",
    states: [
      "Artigas",
      "Canelones",
      "Cerro Largo",
      "Colonia",
      "Durazno",
      "Flores",
      "Florida",
      "Lavalleja",
      "Maldonado",
      "Montevideo",
      "Paysandú",
      "Río Negro",
      "Rivera",
      "Rocha",
      "Salto",
      "San José",
      "Soriano",
      "Tacuarembó",
      "Treinta y Tres",
    ],
  },
  Uzbekistan: {
    isd: "+998",
    iso2: "UZ",
    states: [
      "Andijan",
      "Bukhara",
      "Fergana",
      "Jizzakh",
      "Karakalpakstan",
      "Kashkadarya",
      "Khorezm",
      "Namangan",
      "Navoiy",
      "Samarkand",
      "Sirdaryo",
      "Surxondaryo",
      "Tashkent",
      "Tashkent City",
    ],
  },
  Vanuatu: {
    isd: "+678",
    iso2: "VU",
    states: ["Malampa", "Penama", "Sanma", "Shefa", "Tafea", "Torba"],
  },
  Venezuela: {
    isd: "+58",
    iso2: "VE",
    states: [
      "Amazonas",
      "Anzoátegui",
      "Apure",
      "Aragua",
      "Barinas",
      "Bolívar",
      "Carabobo",
      "Cojedes",
      "Delta Amacuro",
      "Dependencias Federales",
      "Distrito Capital",
      "Falcón",
      "Guárico",
      "La Guaira",
      "Lara",
      "Mérida",
      "Miranda",
      "Monagas",
      "Nueva Esparta",
      "Portuguesa",
      "Sucre",
      "Táchira",
      "Trujillo",
      "Yaracuy",
      "Zulia",
    ],
  },
  Vietnam: {
    isd: "+84",
    iso2: "VN",
    states: [
      "An Giang",
      "Bà Rịa-Vũng Tàu",
      "Bắc Giang",
      "Bắc Kạn",
      "Bạc Liêu",
      "Bắc Ninh",
      "Bến Tre",
      "Bình Định",
      "Bình Dương",
      "Bình Phước",
      "Bình Thuận",
      "Cà Mau",
      "Cần Thơ",
      "Cao Bằng",
      "Đà Nẵng",
      "Đắk Lắk",
      "Đắk Nông",
      "Điện Biên",
      "Đồng Nai",
      "Đồng Tháp",
      "Gia Lai",
      "Hà Giang",
      "Hà Nam",
      "Hà Nội",
      "Hà Tĩnh",
      "Hải Dương",
      "Hải Phòng",
      "Hậu Giang",
      "Hòa Bình",
      "Hồ Chí Minh",
      "Hưng Yên",
      "Khánh Hòa",
      "Kiên Giang",
      "Kon Tum",
      "Lai Châu",
      "Lâm Đồng",
      "Lạng Sơn",
      "Lào Cai",
      "Long An",
      "Nam Định",
      "Nghệ An",
      "Ninh Bình",
      "Ninh Thuận",
      "Phú Thọ",
      "Phú Yên",
      "Quảng Bình",
      "Quảng Nam",
      "Quảng Ngãi",
      "Quảng Ninh",
      "Quảng Trị",
      "Sóc Trăng",
      "Sơn La",
      "Tây Ninh",
      "Thái Bình",
      "Thái Nguyên",
      "Thanh Hóa",
      "Thừa Thiên-Huế",
      "Tiền Giang",
      "Trà Vinh",
      "Tuyên Quang",
      "Vĩnh Long",
      "Vĩnh Phúc",
      "Yên Bái",
    ],
  },
  Yemen: {
    isd: "+967",
    iso2: "YE",
    states: [
      "Abyan",
      "Aden",
      "Al Bayda",
      "Al Hudaydah",
      "Al Jawf",
      "Al Mahrah",
      "Al Mahwit",
      "Amanat Al Asimah",
      "Amran",
      "Dhamar",
      "Hadhramaut",
      "Hajjah",
      "Ibb",
      "Lahij",
      "Ma'rib",
      "Raymah",
      "Sa'dah",
      "Sana'a",
      "Shabwah",
      "Socotra",
      "Taizz",
    ],
  },
  Zambia: {
    isd: "+260",
    iso2: "ZM",
    states: [
      "Central",
      "Copperbelt",
      "Eastern",
      "Luapula",
      "Lusaka",
      "Muchinga",
      "Northern",
      "North-Western",
      "Southern",
      "Western",
    ],
  },
  Zimbabwe: {
    isd: "+263",
    iso2: "ZW",
    states: [
      "Bulawayo",
      "Harare",
      "Manicaland",
      "Mashonaland Central",
      "Mashonaland East",
      "Mashonaland West",
      "Masvingo",
      "Matabeleland North",
      "Matabeleland South",
      "Midlands",
    ],
  },
};

export const COUNTRY_OPTIONS = Object.keys(COUNTRY_META).sort();

export const getISD = (countryName) => COUNTRY_META[countryName]?.isd ?? "";
export const getISO2 = (countryName) => COUNTRY_META[countryName]?.iso2 ?? "";
export const getStates = (countryName) =>
  COUNTRY_META[countryName]?.states ?? [];
